version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: todo-backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: http://backend:8000
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"


