services:
  # FastAPI dev container (built image, still reloads)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://app:app@postgres:5432/todo
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=dev-secret-change-me
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
      - KAFKA_BROKER=redpanda:9092
      - KAFKA_TOPIC=todo-events
    depends_on:
      - postgres
      - redis
      - redpanda

  # Next.js dev container (built image, HMR)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend

  # Postgres placeholder for later phases
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis placeholder for later phases
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  # Redpanda (Kafka-compatible) for local development
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --node-id 0 --check=false --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda:/var/lib/redpanda/data

volumes:
  pgdata:
  redisdata:
  redpanda:


