name: CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  BACKEND_IMAGE: todo-backend
  FRONTEND_IMAGE: todo-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.BACKEND_IMAGE }}:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/${{ env.BACKEND_IMAGE }}:$IMAGE_TAG

      - name: Build and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.FRONTEND_IMAGE }}:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/${{ env.FRONTEND_IMAGE }}:$IMAGE_TAG

      - name: Force new deployment (backend)
        env:
          CLUSTER_NAME: todo-dev-cluster
          SERVICE_NAME: todo-backend-svc
        run: |
          aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --force-new-deployment || true

      - name: Force new deployment (frontend)
        env:
          CLUSTER_NAME: todo-dev-cluster
          SERVICE_NAME: todo-frontend-svc
        run: |
          aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --force-new-deployment || true


