name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          pytest -q backend/tests

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint --silent

  build-images:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-lint]
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t todo-backend:ci ./backend
      - name: Build frontend image
        run: docker build -t todo-frontend:ci ./frontend


